name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Claude Mobile better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's frustrating or missing today?
      placeholder: "I often need to ... but currently there's no way to ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe what you'd like to see. Be as specific as possible.
      placeholder: "Add a button that ... / Support for ... / When X happens, do Y ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches? (optional)

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the app does this relate to?
      options:
        - Terminal
        - Connection / SSH
        - File Management
        - Settings / Preferences
        - Home Screen Widget
        - UI / Theming
        - Other
    validations:
      required: true
